### ISSUE TITLE
Improve Documentation for LDES Ingest Demo

### ISSUE THREAD

**Issue by Krieke** [Informatievlaanderen/VSDS-LDES-E2E-testing#51]
The current documentation is insufficient enough to reproduce the demo as given on 02082022.

Missing LDES server configuration values. (it might be that this can be chosen freely, but on the other hand the purpose is to replicate the demo so all specific configuration settings used during the demo should be described or at least filled in the env.ingest file.
- LDES_COLLECTIONNAME=
- LDES_MEMBERTYPE=
- LDES_SHAPE=
Missing gtfs2ldes configuration values. During the demo it was noticed that it involved a download data set, which. I presume it is the configuration as how it is described on the gtfs2ldes-js repository? OK maybe this can be easily mentioned that these configuration options are a direct mapping to this repository.
- GTFS2LDES_DATA_FOLDER=
- GTFS_SOURCE_FILE=
- GTFSRT_SOURCE=

In the end one needs to be able to reproduce the demo and with the current documented configuration this is not possible.

**Comment by Krieke** [comment]
IMHO there is still a lot more room for improvement to reproduce the exact demo scenario. There is a difference that one knows that different GTFS's can be downloaded or a specific configuration, including all data sets can be used to reproduce each time this demo test case. Know one can chose V1 or V2 data from the lijn, which data might impact the content etc etc. 

There was a data set used during the demo and there was a configuration configured. Why not make that the reference for this test case? It is good that one explains that other data sets can be used but the eccens is to reproduce the demo and with the current information one does not know how to reproduce the demo.

**Comment by Yalz** [comment]
Hi Daniel, 
For the demo, we used the following env. file : [nmbs](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/use-cases/gtfs-and-rt/1.ingest-ldes/env.nmbs) 
This contains all needed properties for that setup

**Comment by Krieke** [comment]
@Yalz can I then also get the data set file used?

**Comment by Krieke** [comment]
@Yalz Thank you for pointing out that there currently is no need to use a local file as showed during the demo of 01/08 and that one can just configure the source endpoints in the GTFS2LDES.

**Comment by Krieke** [comment]
Update on this ticket. The documentation is not complete enough, one has to figure out by questioning the development team how to produce the actual demo of 01/08. It might also be good to actually explain the existence of the specific configuration files env.delijn en env.nmbs

**Comment by rorlic** [comment]
You commented on August 15th. Did you read the documentation from August 8th? Most of your questions and concerns have been answered [here](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/6e62f5158bd0aff949328ade69daf5bb8db73969/e2e-test/use-cases/gtfs-and-rt/1.ingest-ldes#test-setup).

Concerning _the specific configuration files env.delijn en env.nbms_: see above documentation, paragraph 1.

Concerning _why the NMBS gtfs data is coming from a .de demain_: because the data is not publicly available on the NMBS website (unless you [request access](https://www.belgiantrain.be/nl/support/forms/public-data), which we did, some time ago and had to search for it elsewhere as we did not receive access to date).

Concerning _API key is hardcoded in the configuration files_: could you point us to a specific configuration file? Are you referring to this [file](https://github.com/julianrojas87/gtfs2ldes-js/blob/main/conf.env)? This repo does not belong to this team. Please see its owner.

Concerning _it would be better to document where and how to request the API token for this specific data set_: no API is needed for the NMBS data. If you are referring to the De Lijn data, see above documentation, note 2 (and in the specific configuration [file](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/6e62f5158bd0aff949328ade69daf5bb8db73969/e2e-test/use-cases/gtfs-and-rt/1.ingest-ldes/env.delijn), see the last line).

Concerning _env.nmbs contains a configuration to a local mongodb which in a clean environment doesn't exist_: indeed, this is an example configuration file referring to a folder in your home folder on your local machine. Again, see above, note 1.

**Comment by zargha** [comment]
@rorlic will re-open this issue and change the title to *improve documentation just for visibility.

**Comment by rorlic** [comment]
Folder create instructions have been added.
